# Generated by Django 5.2.1 on 2025-05-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_materia_docente_materia_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='docentes',
        ),
    ]
