# Generated by Django 5.2.1 on 2025-05-19 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_materia_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='curso',
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asociadas', to='core.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asociados', to='core.materia')),
            ],
        ),
    ]
