# Generated by Django 5.2.1 on 2025-05-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cursomateriadocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(related_name='cursos', through='core.CursoMateria', to='core.materia'),
        ),
    ]
