# Generated by Django 5.2.1 on 2025-05-23 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_cursomateriadocente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=20)),
                ('dimension', models.CharField(choices=[('ser', 'Ser'), ('saber', 'Saber'), ('hacer', 'Hacer'), ('decidir', 'Decidir')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=20)),
                ('nota', models.FloatField(default=0)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
            options={
                'unique_together': {('curso', 'materia', 'alumno', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='NotaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.evaluacionactividad')),
            ],
            options={
                'unique_together': {('evaluacion', 'alumno')},
            },
        ),
    ]
