# Generated by Django 5.2.1 on 2025-06-01 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cursomateriadocente'),
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_trim1', models.FloatField(help_text='Nota final del 1er trimestre')),
                ('nota_trim2', models.FloatField(help_text='Nota final del 2do trimestre')),
                ('nota_trim3', models.FloatField(help_text='Nota final del 3er trimestre')),
                ('año_académico', models.CharField(blank=True, help_text="Etiqueta de año o cohorte (opcional). Ej: '2023-I'.", max_length=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se insertó este registro histórico.')),
                ('alumno', models.ForeignKey(help_text="Usuario con rol 'alumno'.", limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(help_text='Curso en el que cursó la materia.', on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('materia', models.ForeignKey(help_text='Materia cursada.', on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
        ),
    ]
