# Generated by Django 5.2.1 on 2025-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('director', 'Director'), ('docente', 'Docente'), ('alumno', 'Alumno')], max_length=20),
        ),
    ]
