# Generated by Django 5.2.1 on 2025-05-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('docente', 'Docente'), ('alumno', 'Alumno')], max_length=20),
        ),
    ]
