# Generated by Django 5.2.1 on 2025-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_materia_docentes'),
        ('teachers', '0002_docente_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='docentes_asignados', to='core.materia'),
        ),
    ]
