# Generated by Django 5.2.1 on 2025-05-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_docente_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='materias',
        ),
    ]
